//! Private multisig program.
//!
//! Shielded-voting + ZK-threshold variant of `lez-multisig`. The public
//! version authenticates votes by LEZ signer checks on named member
//! accounts; this one authenticates votes by a Risc0 membership receipt
//! with a scoped nullifier, and leaves the member set on-chain as just a
//! Merkle root.
//!
//! The instruction dispatch is generated by the `#[lez_program]` macro
//! from the `multisig_core::Instruction` enum. Each handler lives in its
//! own file and is invoked by the macro-wrapped function below.

pub mod approve;
pub mod create_multisig;
pub mod execute;
pub mod propose;
pub mod propose_config;
pub mod reject;
pub mod verify;

use multisig_core::{ConfigAction, MembershipJournal};
use nssa_core::program::ProgramId;
use spel_framework::prelude::*;
use zk_common::MerkleRoot;

#[lez_program(instruction = "multisig_core::Instruction")]
mod multisig_program {
    use super::*;

    /// Create a new M-of-N private multisig. The creator publishes only a
    /// Merkle root over member commitments — no member identities are
    /// stored on-chain.
    #[instruction]
    pub fn create_multisig(
        #[account(init, pda = arg("create_key"))]
        multisig_state: AccountWithMetadata,
        create_key: [u8; 32],
        threshold: u8,
        member_count: u8,
        members_root: MerkleRoot,
    ) -> SpelResult {
        let accounts = vec![multisig_state];
        let (accounts_out, chained_calls) =
            crate::create_multisig::handle(&accounts, &create_key, threshold, member_count, &members_root);
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }

    /// Propose a ChainedCall. No proposer account is attached; the proof
    /// itself is the authorization.
    #[instruction]
    pub fn propose(
        #[account(mut)]
        multisig_state: AccountWithMetadata,
        #[account(init, pda = [literal("multisig_prop___"), arg("create_key"), arg("proposal_index")])]
        proposal: AccountWithMetadata,
        target_program_id: ProgramId,
        target_instruction_data: Vec<u32>,
        target_account_count: u8,
        pda_seeds: Vec<[u8; 32]>,
        authorized_indices: Vec<u8>,
        create_key: [u8; 32],
        proposal_index: u64,
        membership_journal: MembershipJournal,
    ) -> SpelResult {
        let accounts = vec![multisig_state, proposal];
        let (accounts_out, chained_calls) = crate::propose::handle(
            &accounts,
            &target_program_id,
            &target_instruction_data,
            target_account_count,
            &pda_seeds,
            &authorized_indices,
            proposal_index,
            &membership_journal,
        );
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }

    #[instruction]
    pub fn approve(
        #[account(mut)]
        multisig_state: AccountWithMetadata,
        #[account(mut, pda = [literal("multisig_prop___"), arg("create_key"), arg("proposal_index")])]
        proposal: AccountWithMetadata,
        proposal_index: u64,
        create_key: [u8; 32],
        membership_journal: MembershipJournal,
    ) -> SpelResult {
        let accounts = vec![multisig_state, proposal];
        let (accounts_out, chained_calls) =
            crate::approve::handle(&accounts, proposal_index, &membership_journal);
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }

    #[instruction]
    pub fn reject(
        #[account(mut)]
        multisig_state: AccountWithMetadata,
        #[account(mut, pda = [literal("multisig_prop___"), arg("create_key"), arg("proposal_index")])]
        proposal: AccountWithMetadata,
        proposal_index: u64,
        create_key: [u8; 32],
        membership_journal: MembershipJournal,
    ) -> SpelResult {
        let accounts = vec![multisig_state, proposal];
        let (accounts_out, chained_calls) =
            crate::reject::handle(&accounts, proposal_index, &membership_journal);
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }

    /// Execute is permissionless — no signer, no membership proof. The
    /// threshold-many nullifiers already accumulated on the proposal are
    /// the authorization.
    #[instruction]
    pub fn execute(
        #[account(mut)]
        multisig_state: AccountWithMetadata,
        #[account(mut, pda = [literal("multisig_prop___"), arg("create_key"), arg("proposal_index")])]
        proposal: AccountWithMetadata,
        target_accounts: Vec<AccountWithMetadata>,
        proposal_index: u64,
        create_key: [u8; 32],
    ) -> SpelResult {
        let mut accounts = vec![multisig_state, proposal];
        accounts.extend(target_accounts);
        let (accounts_out, chained_calls) = crate::execute::handle(&accounts, proposal_index);
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }

    #[instruction]
    pub fn propose_add_member(
        #[account(mut)]
        multisig_state: AccountWithMetadata,
        #[account(init, pda = [literal("multisig_prop___"), arg("create_key"), arg("proposal_index")])]
        proposal: AccountWithMetadata,
        new_commitment: [u8; 32],
        expected_new_root: MerkleRoot,
        create_key: [u8; 32],
        proposal_index: u64,
        membership_journal: MembershipJournal,
    ) -> SpelResult {
        let accounts = vec![multisig_state, proposal];
        let (accounts_out, chained_calls) = crate::propose_config::handle(
            &accounts,
            ConfigAction::AddMember {
                new_commitment,
                expected_new_root,
            },
            proposal_index,
            &membership_journal,
        );
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }

    #[instruction]
    pub fn propose_remove_member(
        #[account(mut)]
        multisig_state: AccountWithMetadata,
        #[account(init, pda = [literal("multisig_prop___"), arg("create_key"), arg("proposal_index")])]
        proposal: AccountWithMetadata,
        target_commitment: [u8; 32],
        expected_new_root: MerkleRoot,
        create_key: [u8; 32],
        proposal_index: u64,
        membership_journal: MembershipJournal,
    ) -> SpelResult {
        let accounts = vec![multisig_state, proposal];
        let (accounts_out, chained_calls) = crate::propose_config::handle(
            &accounts,
            ConfigAction::RemoveMember {
                target_commitment,
                expected_new_root,
            },
            proposal_index,
            &membership_journal,
        );
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }

    #[instruction]
    pub fn propose_change_threshold(
        #[account(mut)]
        multisig_state: AccountWithMetadata,
        #[account(init, pda = [literal("multisig_prop___"), arg("create_key"), arg("proposal_index")])]
        proposal: AccountWithMetadata,
        new_threshold: u8,
        create_key: [u8; 32],
        proposal_index: u64,
        membership_journal: MembershipJournal,
    ) -> SpelResult {
        let accounts = vec![multisig_state, proposal];
        let (accounts_out, chained_calls) = crate::propose_config::handle(
            &accounts,
            ConfigAction::ChangeThreshold { new_threshold },
            proposal_index,
            &membership_journal,
        );
        Ok(SpelOutput::execute(accounts_out, chained_calls))
    }
}
