#!/usr/bin/env python3
"""
================================================================================
ROCA VULNERABILITY LAB  (CVE-2017-15361 / "Return of Coppersmith's Attack")
A hands-on teaching module for an undergraduate security course.
================================================================================

WHAT THIS LAB SHOWS
-------------------
Infineon's RSALib (used in many smartcards and TPMs, ~2012-2017) generated RSA
primes with a hidden structure:

        p  =  k * M  +  (65537 ^ x  mod  M)

where M is a "primorial" (the product of the first n primes) and x is a small
secret exponent. A standards-conformant RSA prime is supposed to be ~uniformly
random. This structure is NOT random, and it has two devastating consequences:

  1. DETECTION: anyone can tell a key is vulnerable *from the public key alone*,
     because N = p*q must lie in the small multiplicative subgroup generated by
     65537 modulo M. A good RSA key would almost never land in that subgroup.

  2. FACTORIZATION: the secret exponent x has very low entropy, so the private
     key can be recovered far faster than factoring a proper RSA modulus.

THE CERTIFICATION LESSON (tie-in to Common Criteria lecture)
------------------------------------------------------------
The affected chips held Common Criteria certificates issued by BSI, evaluated by
an accredited lab. The Security Target claimed RSA keys were generated per a
recognized standard. The fingerprint test below *proves from public data* that
they were not. CC evaluation verifies claims against evidence -- it does not
independently re-derive the mathematics of an undisclosed proprietary algorithm.
ROCA is the textbook example of "certified" not meaning "secure".

SCOPE / SAFETY NOTE
-------------------
This lab uses DELIBERATELY TINY keys (~110-130 bits) so the attack finishes
instantly in a classroom. The Infineon library has been fixed for years; no new
vulnerable keys are produced. Breaking a real 2048-bit ROCA key needs the full
Coppersmith lattice optimization plus enormous compute (CPU-years). This code
will NOT scale to real keys -- and that limitation is itself a teaching point
discussed at the bottom of the file.

USAGE
-----
    python3 roca_lab.py            # run the full guided demo
Exercises for students are marked with  >>> EXERCISE <<<  throughout.
================================================================================
"""

import random
from math import gcd, isqrt

# ==============================================================================
# SECTION 0 -- Number-theory utilities (read, but you do not need to edit these)
# ==============================================================================

def is_prime(n: int, rounds: int = 40) -> bool:
    """Miller-Rabin probabilistic primality test."""
    if n < 2:
        return False
    for sp in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % sp == 0:
            return n == sp
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for _ in range(rounds):
        a = random.randrange(2, n - 1)
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(s - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def first_primes(count: int) -> list:
    """Return the first `count` prime numbers."""
    out, n = [], 2
    while len(out) < count:
        if all(n % p for p in out):
            out.append(n)
        n += 1
    return out


def factorize(n: int) -> dict:
    """Trial-division factorization (only used on small, smooth numbers here)."""
    f, d = {}, 2
    while d * d <= n:
        while n % d == 0:
            f[d] = f.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        f[n] = f.get(n, 0) + 1
    return f


def multiplicative_order(g: int, M: int) -> int:
    """Smallest positive e with g**e == 1 (mod M)."""
    # The order divides lambda(M) = lcm(p_i - 1) for M = product of primes p_i.
    lam_factors = {}
    for p in factorize(M):                       # M is square-free here
        for q, e in factorize(p - 1).items():
            lam_factors[q] = max(lam_factors.get(q, 0), e)
    order = 1
    for q, e in lam_factors.items():
        order *= q ** e
    for q in lam_factors:                        # strip prime factors that are not needed
        while order % q == 0 and pow(g, order // q, M) == 1:
            order //= q
    return order


def discrete_log_bsgs(g: int, h: int, M: int, bound: int):
    """
    Baby-step / giant-step: find x in [0, bound) with g**x == h (mod M),
    or return None. Runs in about sqrt(bound) steps -- this is why DETECTION
    of a ROCA key is *cheap* even though the subgroup is not microscopic.
    """
    m = isqrt(bound) + 1
    table = {}
    e = 1
    for j in range(m):
        table.setdefault(e, j)
        e = e * g % M
    factor = pow(g, -m, M)                       # modular inverse of g**m
    gamma = h % M
    for i in range(m + 1):
        if gamma in table:
            x = i * m + table[gamma]
            if x < bound:
                return x
        gamma = gamma * factor % M
    return None


# ==============================================================================
# SECTION 1 -- Key generation: build BOTH a ROCA-style key and a healthy key
# ==============================================================================

# --- Lab parameters -----------------------------------------------------------
# M is a primorial. With 14 primes the subgroup is tiny (order 27720), so the
# brute-force attack is instant. Want a slower, more realistic run? Bump this to
# 16 (order ~8.3 million, a few seconds). See >>> EXERCISE 4 <<<.
PRIMORIAL_PRIME_COUNT = 14
GENERATOR = 65537                                # the exact constant Infineon used

PRIMORIAL_PRIMES = first_primes(PRIMORIAL_PRIME_COUNT)
M = 1
for _p in PRIMORIAL_PRIMES:
    M *= _p
SUBGROUP_ORDER = multiplicative_order(GENERATOR, M)


def generate_roca_prime(k_bits: int = 4) -> tuple:
    """
    Generate a prime with the Infineon ROCA structure:
        p = k * M + (GENERATOR**x mod M)
    `x` is the low-entropy secret; `k` is a small cofactor that sets the size.
    Returns (p, x, k).
    """
    while True:
        x = random.randrange(SUBGROUP_ORDER)
        k = random.randrange(1 << (k_bits - 1), 1 << k_bits)
        p = k * M + pow(GENERATOR, x, M)
        if is_prime(p):
            return p, x, k


def generate_roca_key() -> dict:
    """Build a full vulnerable RSA modulus N = p * q from two ROCA primes."""
    p, xp, kp = generate_roca_prime()
    q, xq, kq = generate_roca_prime()
    while q == p:
        q, xq, kq = generate_roca_prime()
    return {"N": p * q, "p": p, "q": q,
            "secret_xp": xp, "secret_xq": xq, "secret_kp": kp, "secret_kq": kq}


def generate_safe_prime(bit_len: int) -> int:
    """Generate an ordinary uniformly-random prime (the way RSA *should* work)."""
    while True:
        cand = random.getrandbits(bit_len) | (1 << (bit_len - 1)) | 1
        if is_prime(cand):
            return cand


def generate_safe_key() -> dict:
    """A healthy RSA modulus of comparable size, for contrast in the demo."""
    bit_len = (M.bit_length() + 4)               # match the ROCA key roughly
    p = generate_safe_prime(bit_len)
    q = generate_safe_prime(bit_len)
    while q == p:
        q = generate_safe_prime(bit_len)
    return {"N": p * q, "p": p, "q": q}


# ==============================================================================
# SECTION 2 -- The fingerprint detector  (THE central learning objective)
# ==============================================================================

def is_roca_vulnerable(N: int) -> tuple:
    """
    Decide -- using ONLY the public modulus N -- whether N was produced by the
    ROCA generator.

    Math: if p = g**xp (mod M) and q = g**xq (mod M), then
          N = p*q = g**(xp+xq) (mod M).
    So N mod M must be an element of the subgroup generated by g modulo M.
    We simply test whether a discrete logarithm of (N mod M) base g exists.

    Returns (vulnerable: bool, a: int|None) where `a = xp + xq mod order`.
    Note `a` is leaked by the *public* key -- already an information leak.
    """
    a = discrete_log_bsgs(GENERATOR, N % M, M, SUBGROUP_ORDER)
    return (a is not None), a


# ==============================================================================
# SECTION 3 -- Entropy analysis: WHY the structure is fatal
# ==============================================================================

def analyse_entropy(prime_bit_len: int, k_bits: int = 4) -> dict:
    """
    Compare the entropy of a ROCA prime against an ideal random prime.
    A ROCA prime is pinned down by (x, k): about log2(order) + k_bits free bits.
    An ideal prime of the same size has ~prime_bit_len free bits.
    """
    roca_free = SUBGROUP_ORDER.bit_length() + k_bits
    ideal_free = prime_bit_len
    return {"roca_free_bits": roca_free,
            "ideal_free_bits": ideal_free,
            "lost_bits": ideal_free - roca_free,
            "search_space_ratio": 2.0 ** (ideal_free - roca_free)}


# ==============================================================================
# SECTION 4 -- The factorization attack (works on the lab's tiny keys)
# ==============================================================================

def factor_roca_key(N: int, k_max: int = 64, verbose: bool = True):
    """
    Recover p from a ROCA modulus N.

    Idea: every ROCA prime satisfies  p = k*M + (g**x mod M)  with x in
    [0, SUBGROUP_ORDER) and a SMALL k. Both ranges are tiny, so we just
    enumerate them and test divisibility against N.

        for each candidate exponent x:
            c = g**x mod M                       # = p mod M
            for each small cofactor k:
                if (k*M + c) divides N -> that is p

    The REAL ROCA attack replaces this brute force with Coppersmith's lattice
    method (see notes at the bottom). The principle is identical: the secret x
    has far too little entropy.
    """
    a = discrete_log_bsgs(GENERATOR, N % M, M, SUBGROUP_ORDER)
    if a is None:
        return None                              # not a ROCA key
    if verbose:
        print(f"    leaked exponent sum a = xp+xq = {a}  (from the public key)")
        print(f"    searching {SUBGROUP_ORDER} exponents x {chr(215)} {k_max+1} cofactors k ...")

    for x in range(SUBGROUP_ORDER):
        c = pow(GENERATOR, x, M)
        for k in range(0, k_max + 1):
            cand = k * M + c
            if cand > 1 and N % cand == 0:
                p, q = cand, N // cand
                if 1 < p < N:
                    return p, q, x
    return None


# ==============================================================================
# SECTION 5 -- Guided demo
# ==============================================================================

def banner(title: str) -> None:
    print("\n" + "=" * 78 + f"\n  {title}\n" + "=" * 78)


def main() -> None:
    random.seed()                                # remove the arg for reproducible runs

    banner("LAB SETUP")
    print(f"  Generator g           : {GENERATOR}")
    print(f"  Primorial M           : product of first {PRIMORIAL_PRIME_COUNT} primes")
    print(f"  Primes in M           : {PRIMORIAL_PRIMES}")
    print(f"  bit-length of M       : {M.bit_length()}")
    print(f"  subgroup order ord(g) : {SUBGROUP_ORDER}  ({SUBGROUP_ORDER.bit_length()} bits)")

    # ---- Build the two keys --------------------------------------------------
    banner("STEP 1 -- Generate one VULNERABLE key and one HEALTHY key")
    vuln = generate_roca_key()
    safe = generate_safe_key()
    print(f"  Vulnerable N ({vuln['N'].bit_length()} bits): {vuln['N']}")
    print(f"  Healthy    N ({safe['N'].bit_length()} bits): {safe['N']}")
    print(f"  (secret ROCA exponents -- not known to an attacker: "
          f"xp={vuln['secret_xp']}, xq={vuln['secret_xq']})")

    # ---- Fingerprint detection ----------------------------------------------
    banner("STEP 2 -- Fingerprint test using ONLY the public modulus")
    v_hit, v_a = is_roca_vulnerable(vuln["N"])
    s_hit, s_a = is_roca_vulnerable(safe["N"])
    print(f"  Vulnerable key -> ROCA detected? {v_hit}   (recovered a = {v_a})")
    print(f"  Healthy    key -> ROCA detected? {s_hit}   (recovered a = {s_a})")
    print("  Lesson: the structure is visible from the PUBLIC key. A conformant")
    print("          RSA modulus would (almost) never fall in this subgroup.")

    # ---- Entropy analysis ----------------------------------------------------
    banner("STEP 3 -- Why the structure is fatal: entropy of the secret")
    ent = analyse_entropy(vuln["p"].bit_length())
    print(f"  An ideal {vuln['p'].bit_length()}-bit prime  : ~{ent['ideal_free_bits']} bits of entropy")
    print(f"  A ROCA prime of that size : ~{ent['roca_free_bits']} bits of entropy")
    print(f"  Entropy destroyed         : ~{ent['lost_bits']} bits")
    print(f"  => attacker's search space shrinks by a factor of "
          f"~2^{ent['lost_bits']} ({ent['search_space_ratio']:.3e})")

    # ---- Factorization -------------------------------------------------------
    banner("STEP 4 -- Recover the private key by factoring N")
    print("  Attacking the vulnerable key:")
    result = factor_roca_key(vuln["N"])
    if result:
        f1, f2, x = result
        ok = (f1 * f2 == vuln["N"])
        # The search finds whichever factor has the smaller exponent first;
        # match it back to the generator's secrets so the report is unambiguous.
        true_x = vuln["secret_xp"] if f1 == vuln["p"] else vuln["secret_xq"]
        print(f"    FACTORED:  factor 1 = {f1}")
        print(f"               factor 2 = {f2}")
        print(f"    f1 * f2 == N verified? {ok}")
        print(f"    recovered secret exponent x of factor 1: {x} "
              f"(generator's true value: {true_x})  -> match: {x == true_x}")
    else:
        print("    factorization failed -- widen k_max and retry")

    print("\n  Attacking the healthy key (should fail fast):")
    print(f"    result: {factor_roca_key(safe['N'], verbose=False)}  "
          f"(None == cannot attack a properly generated key)")

    banner("DONE")
    print("  You broke a ROCA key end to end: detect -> quantify -> factor.\n")


# ==============================================================================
# >>> STUDENT EXERCISES <<<
# ------------------------------------------------------------------------------
# EXERCISE 1 (detection)
#   Generate 50 healthy keys and 50 ROCA keys. Confirm is_roca_vulnerable() has
#   zero false positives and zero false negatives. Why are false positives so
#   improbable? (Hint: subgroup size vs. the size of the group of units mod M.)
#
# EXERCISE 2 (cost of detection)
#   discrete_log_bsgs runs in ~sqrt(order) steps. Time the detector as you raise
#   PRIMORIAL_PRIME_COUNT. Detection stays cheap even when the attack gets slow
#   -- explain why a defender can scan millions of public keys quickly.
#
# EXERCISE 3 (the certification angle -- written)
#   The vulnerable chips were Common Criteria certified. Using SECTION 2, argue
#   in one paragraph what an evaluator *could* have caught and what they
#   structurally could not. Where should the assurance have come from instead?
#
# EXERCISE 4 (scaling wall)
#   Set PRIMORIAL_PRIME_COUNT = 16 and rerun. The attack now takes seconds.
#   Estimate the run time for the real Infineon M (primorial ~970 bits, subgroup
#   order ~2^62). Why is naive brute force hopeless, and what does the real
#   attack do instead? (Read the COPPERSMITH note below.)
#
# EXERCISE 5 (defence)
#   Modify generate_roca_prime so the output passes is_roca_vulnerable() == False
#   while keeping it efficient. What is the *minimum* change required, and what
#   does that tell you about the root cause of the bug?
#
# ------------------------------------------------------------------------------
# NOTE -- THE REAL ATTACK (COPPERSMITH), for the curious
# ------------------------------------------------------------------------------
# This lab brute-forces x because the lab's subgroup is tiny. For real Infineon
# keys the subgroup order is ~2^62 -- too large to enumerate. The real attack:
#   * picks a DIVISOR M' of M for which the order of g is small enough to
#     enumerate, trading subgroup size against how much of p is pinned down;
#   * for each candidate it knows p mod M', i.e. a chunk of p's bits;
#   * Coppersmith's method (Howgrave-Graham + LLL lattice reduction) recovers
#     the rest of p in polynomial time once enough bits are known.
# It still cost roughly 97 CPU-days per 1024-bit key / ~140 CPU-years per
# 2048-bit key in the 2017 paper -- feasible for a well-resourced attacker,
# which is exactly why 750,000+ Estonian national ID cards had to be replaced.
# Reference: Nemec, Sys, Svenda, Klinec, Matyas, "The Return of Coppersmith's
# Attack", ACM CCS 2017.
# ==============================================================================

if __name__ == "__main__":
    main()
